### ISSUE TITLE
Add 'epoch number' to stats.csv from dumper

### ISSUE THREAD

**Issue by jason-james** [iotexproject/iotex-election#30]
If I am not mistaken, the dumper tool is showing a snapshot of our voter buckets at the time the tool was run. 

Could you add an 'Epoch number' field to tell us which epoch the snapshot was taken in? Where epoch number 0 = genesis block, 1 = next epoch and so on. 

I want to pull the data from the dumper each day and import it into my database, it will be clearer to use if I know which epoch the snapshot is from, otherwise there can be a lot of duplicates

Edit: More importantly, adding an 'iotex address' column to the dumper output would really help us to write robust auto reward scripts. I will not make a separate issue for this but I hope it can be implemented. I know the iotex addresses are in the processor output but that output lacks information compared to stats.csv, so I have decided to base my script on stats.csv, but it needs the iotex address. Adding an epoch number isn't as important.

**Comment by jason-james** [comment]
Updated op (see edit)

**Comment by CoderZhi** [comment]
@jason-james thanks for your input. Let me jump to the conclusion first: no, we cannot add epoch number in the dumper. iotex-election is an add-on of the gravity chain (which is Ethereum for now), which collects the election results happens on the gravity chain. Thus, you can consider it as part of the gravity chain. Therefore, iotex-election is not able to tell what the epoch of iotex-core.

To achieve what you want to do, you may follow these steps:
1. Query on iotex-core for the gravity chain height by epoch number
2. With the gravity chain height for the given epoch number, use the dumper with flag "height" 

Hope my answer could resolve your problem.
